import libs = gmock%lib{gmock}

cxx.poptions += "-I$src_base"

exe{driver}: test/cxx{gmock_all_test} hxx{**} $libs
exe{driver}: test/cxx{** -gmock_all_test}: include = false

# C1128: number of sections exceeded object file format limit: compile with
# /bigobj
#
if ($cxx.id == 'msvc')
  test/obje{gmock_all_test}: cxx.coptions += /bigobj
