
build_static = ($config.bin.lib == both || $config.bin.lib == static)
build_shared = ($config.bin.lib == both || $config.bin.lib == shared)

import gtest_main = gtest%liba{gtest_main}

cxx{*main}: extension = cxx
if ($build_shared)
{
  import gtest_dynamic = gtest%libs{gtest}
  ./ : exe{basic-gtest_dynamic_main} : cxx{no_main} $gtest_dynamic $gtest_main 
  ./ : exe{basic-gtest_dynamic}      : cxx{main}  	$gtest_dynamic
}

if ($build_static)
{
  import gtest_static = gtest%liba{gtest}
  ./ : exe{basic-gtest_static_main}  : cxx{no_main} $gtest_static  $gtest_main 
  ./ : exe{basic-gtest_static}       : cxx{main}    $gtest_static
}





