
#############################################################
# Google Test's own tests.

# The following commented lines were for tests-as-sub-project case which cannot work because sources are out of (sub-)project :/
import lib_gtest = gtest%lib{gtest}
import lib_gtest_main = gtest%liba{gtest_main}

# Note: we reflect the content of CMake's scripts, which apparently do not take
# all sources into account, so no loop.

test_names_with_gtest_main =  googletest-death-test-test           \
                              googletest-filepath-test             \
                              gtest_main_unittest                  \
                              googletest-message-test              \
                              googletest-options-test              \
                              googletest-port-test                 \
                              gtest_pred_impl_unittest             \
                              googletest-test-part-test            \
                              gtest_unittest                       \
                              gtest_sole_header_test               \
                              googletest-printers-test             \
                              gtest_skip_test     

test_names_with_gtest      =  gtest_environment_test               \
                              gtest_no_test_unittest               \
                              gtest_premature_exit_test            \
                              gtest_repeat_test                    \
                              gtest_stress_test                    \
                              gtest_throw_on_failure_ex_test       \
                              gtest-unittest-api_test              \
                              gtest_skip_in_environment_setup_test \
                              googletest-listener-test         # This one was linking with gtest_main in Cmake but it have a main() so it does not link.

all_tests_names = $test_names_with_gtest_main $test_names_with_gtest

for test_name : $all_tests_names
{
  # info "GTEST TEST: $test_name"
  ./ : exe{$test_name} : cxx{$test_name} hxx{**}
}

exe{*}:
{
  dist = false
  install = false # Don't install tests
  test = true # We want to run these tests when testing.
}

exe{$test_names_with_gtest_main} : $lib_gtest $lib_gtest_main
exe{$test_names_with_gtest}      : $lib_gtest

# Special cases:
exe{googletest-param-test-test} : cxx{googletest-param-test-test googletest-param-test2-test} $lib_gtest
exe{gtest-typed-test_test} : cxx{gtest-typed-test_test gtest-typed-test2_test} $lib_gtest $lib_gtest_main
exe{gtest_prod_test} : cxx{gtest_prod_test production} $lib_gtest $lib_gtest_main