
import gtest_main = googletest%liba{gtest_main}
import gtest_dynamic = googletest%libs{gtest}
import gtest_static = googletest%liba{gtest}

./ : exe{basic-gtest_dynamic_main} : cxx{no_main} $gtest_dynamic $gtest_main
./ : exe{basic-gtest_static_main}  : cxx{no_main} $gtest_static  $gtest_main

./ : exe{basic-gtest_dynamic}      : cxx{main}  	$gtest_dynamic
./ : exe{basic-gtest_static}       : cxx{main}    $gtest_static


